name: CI/CD Pipeline for AccountService and TransactionService

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job for accountService
  test-account-service:
    name: Test accountService
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          cd accountService
          npm install

      - name: Run tests
        run: |
          cd accountService
          npm test

  deploy-account-service:
    name: Deploy accountService to Heroku
    runs-on: ubuntu-latest
    needs: test-account-service
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          cd accountService
          npm install

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: your-account-service-heroku-app-name
        run: |
          cd accountService
          git remote add heroku https://git.heroku.com/${{ env.HEROKU_APP_NAME }}.git
          git push heroku main

  # Job for transactionService
  test-transaction-service:
    name: Test transactionService
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          cd transactionService
          npm install

      - name: Run tests
        run: |
          cd transactionService
          npm test

  deploy-transaction-service:
    name: Deploy transactionService to Heroku
    runs-on: ubuntu-latest
    needs: test-transaction-service
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          cd transactionService
          npm install

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: your-transaction-service-heroku-app-name
        run: |
          cd transactionService
          git remote add heroku https://git.heroku.com/${{ env.HEROKU_APP_NAME }}.git
          git push heroku main
