name: CI/CD Pipeline for AccountService and TransactionService

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-account-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
        working-directory: Solution/backend/accountService
      - run: npm test
        working-directory: Solution/backend/accountService

  test-transaction-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
        working-directory: Solution/backend/transactionService
      - run: npm test
        working-directory: Solution/backend/transactionService

  deploy-account-service:
    needs: test-account-service
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Heroku AccountService
        run: git push https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/your-account-service-heroku-app-name.git HEAD:main
        working-directory: Solution/backend/accountService

  deploy-transaction-service:
    needs: test-transaction-service
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Heroku TransactionService
        run: git push https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/your-transaction-service-heroku-app-name.git HEAD:main
        working-directory: Solution/backend/transactionService
