name: CI/CD Pipeline for AccountService and TransactionService

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-account-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Dependencies
        run: npm install
        working-directory: Solution/backend/accountService
      - name: Run Tests
        run: npm test
        working-directory: Solution/backend/accountService

  test-transaction-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Dependencies
        run: npm install
        working-directory: Solution/backend/transactionService
      - name: Run Tests
        run: npm test
        working-directory: Solution/backend/transactionService

  deploy-account-service:
    needs: test-account-service
    runs-on: ubuntu-latest
    steps:
   
